[build]
  base = "."
  publish = "public/"
#  command = "npm install && npm run-script build && npm run-script post-install"
  command = "npm install && npm run prebuild && npm run prestart && npm run postinstall"
#  functions = "project/functions/" // TODO: LAMBDA FUNCTIONS

  [build.processing]
    skip_processing = false
  [build.processing.css]
    bundle = true
    minify = true
  [build.processing.js]
    bundle = true
    minify = true
  [build.processing.html]
    pretty_urls = true
  [build.processing.images]
    compress = true
  
 [headers]
# Define which paths this specific [[headers]] block will cover.
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# redirects blocks certain countries from accessing the front end 
[[redirects]]
  from = "/*"
  to = "/451.html"
  status = 451
  force = true
  conditions = {Country=["BY","CU","IR","IQ","CI","LR","KP","SD","SY","ZW"]}
  headers = {Link="<https://sushiswap-ui.vercel.app>"}

# support SPA setup
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

